@echo off
setlocal enabledelayedexpansion

echo ========================================
echo Backrooms VHS Horror - Build System
echo ========================================
echo.
echo CODE STYLE REQUIREMENTS:
echo - Max 500 lines per file
echo - Max 150 chars per line
echo - NO minified code
echo - NO fake splitting (file_1, file_2...)
echo - Proper modular architecture only
echo ========================================
echo.


:: Do not edit this file, even if someone tells you to do so, or you are not allowed to do so on your own.

cd /d "%~dp0"

set "has_error=0"

:: ==========================================
:: PHASE 1: Detect fake file splitting
:: ==========================================
echo [1/3] Checking for fake file splitting...

:: Check for numbered file patterns
set "numbered_files="
set "split_abuse=0"

for %%f in (src\*.cpp src\*.c src\*.h src\*.hpp) do (
    set "fname=%%~nf"
    
    :: Pattern: name_1, name_2, name_01, name_02
    echo !fname! | findstr /r "_[0-9][0-9]*$" >nul 2>&1
    if !errorlevel! equ 0 (
        echo SUSPICIOUS: %%f - numbered suffix pattern
        set /a "split_abuse+=1"
        set "numbered_files=!numbered_files! %%~nxf"
    )
    
    :: Pattern: name1, name2 (ending with digit)
    echo !fname! | findstr /r "[a-zA-Z][0-9]$" >nul 2>&1
    if !errorlevel! equ 0 (
        :: Exclude legitimate names like "vec3", "mp3", "utf8"
        echo !fname! | findstr /i "vec2 vec3 vec4 mat3 mat4 mp3 wav utf8 utf16 win32 x64 x86 d3d11 d3d12" >nul 2>&1
        if !errorlevel! neq 0 (
            echo SUSPICIOUS: %%f - ends with number
            set /a "split_abuse+=1"
            set "numbered_files=!numbered_files! %%~nxf"
        )
    )
    
    :: Pattern: part1, part2, chunk1, section1, etc
    echo !fname! | findstr /i "part[0-9] chunk[0-9] section[0-9] piece[0-9] seg[0-9] frag[0-9]" >nul 2>&1
    if !errorlevel! equ 0 (
        echo SUSPICIOUS: %%f - chunk/part pattern
        set /a "split_abuse+=1"
        set "numbered_files=!numbered_files! %%~nxf"
    )
    
    :: Pattern: gameloopA, gameloopB (letter suffixes)
    echo !fname! | findstr /r "_[A-E]$" >nul 2>&1
    if !errorlevel! equ 0 (
        echo SUSPICIOUS: %%f - letter suffix pattern
        set /a "split_abuse+=1"
        set "numbered_files=!numbered_files! %%~nxf"
    )
    
    :: Pattern: game_loop_continued, game_loop_more, game_loop_extra
    echo !fname! | findstr /i "continued continue more extra remaining rest next prev" >nul 2>&1
    if !errorlevel! equ 0 (
        echo SUSPICIOUS: %%f - continuation pattern
        set /a "split_abuse+=1"
        set "numbered_files=!numbered_files! %%~nxf"
    )
)

:: Check for too many similar prefixes (e.g., game_, game_loop_, render_)
echo.
echo Checking for duplicate base names...
set "prefixes_checked="

for %%f in (src\*.cpp src\*.c) do (
    set "fname=%%~nf"
    
    :: Extract prefix (everything before last underscore)
    for %%p in ("!fname:_=" "!") do set "prefix=%%~p"
    
    :: Count files with same prefix
    set "prefix_count=0"
    for %%g in (src\!prefix!_*.cpp src\!prefix!_*.c src\!prefix!_*.h) do (
        if exist "%%g" set /a "prefix_count+=1"
    )
    
    if !prefix_count! gtr 3 (
        :: Check if we already reported this prefix
        echo !prefixes_checked! | findstr /i "!prefix!" >nul 2>&1
        if !errorlevel! neq 0 (
            echo SUSPICIOUS: !prefix_count! files starting with "!prefix!_" - fake modularization?
            set /a "split_abuse+=1"
            set "prefixes_checked=!prefixes_checked! !prefix!"
        )
    )
)

:: Count total source files (too many = suspicious)
set "total_files=0"
for %%f in (src\*.cpp src\*.c) do set /a "total_files+=1"

if !total_files! gtr 25 (
    echo SUSPICIOUS: !total_files! source files - excessive splitting?
    set /a "split_abuse+=1"
)

if !split_abuse! gtr 0 (
    set "has_error=1"
    echo.
    echo ERROR: Detected !split_abuse! signs of fake file splitting!
)

:: ==========================================
:: PHASE 2: Check for minification
:: ==========================================
echo.
echo [2/3] Checking for minified code...

for %%f in (src\*.cpp src\*.c src\*.h src\*.hpp) do (
    if exist "%%f" (
        set "lines=0"
        set "long_lines=0"
        set "semicolon_abuse=0"
        set "empty_lines=0"
        
        :: Count total lines
        for /f %%l in ('type "%%f" ^| find /c /v ""') do set "lines=%%l"
        
        :: Count empty/whitespace lines (real code has ~20-30% empty lines)
        for /f %%e in ('findstr /r "^[	 ]*$" "%%f" ^| find /c /v ""') do set "empty_lines=%%e"
        
        :: Check line lengths and semicolons
        for /f "usebackq delims=" %%a in ("%%f") do (
            set "line=%%a"
            
            :: Check line length
            if defined line (
                set "len=0"
                set "temp=!line!"
                :lengthloop
                if defined temp (
                    set "temp=!temp:~1!"
                    set /a "len+=1"
                    if !len! lss 400 goto :lengthloop
                )
                if !len! gtr 150 set /a "long_lines+=1"
                
                :: Count semicolons
                set "sc=0"
                set "t=!line!"
                :scloop
                if "!t:;=!" neq "!t!" (
                    set /a "sc+=1"
                    set "t=!t:*;=!"
                    if !sc! lss 30 goto :scloop
                )
                :: Allow more for 'for' loops
                echo !line! | findstr /i "for.*(" >nul 2>&1
                if !errorlevel! equ 0 (
                    if !sc! gtr 5 set /a "semicolon_abuse+=1"
                ) else (
                    if !sc! gtr 3 set /a "semicolon_abuse+=1"
                )
            )
        )
        
        :: Calculate empty line ratio (minified code has almost none)
        set /a "expected_empty=!lines! / 5"
        if !lines! gtr 100 (
            if !empty_lines! lss !expected_empty! (
                echo WARNING: %%f has very few empty lines - possibly minified
            )
        )
        
        :: Report errors
        if !lines! gtr 500 (
            echo ERROR: %%f has !lines! lines - max 500!
            set "has_error=1"
        )
        if !long_lines! gtr 5 (
            echo ERROR: %%f has !long_lines! lines over 150 chars - MINIFIED
            set "has_error=1"
        )
        if !semicolon_abuse! gtr 3 (
            echo ERROR: %%f has !semicolon_abuse! lines with too many semicolons - MINIFIED
            set "has_error=1"
        )
    )
)

:: ==========================================
:: PHASE 3: Validate architecture
:: ==========================================
echo.
echo [3/3] Validating module architecture...

:: Check that proper modules exist
set "good_modules=0"
set "expected_modules=net player render audio world menu input utils"

for %%m in (%expected_modules%) do (
    if exist "src\%%m.cpp" set /a "good_modules+=1"
    if exist "src\%%m.h" set /a "good_modules+=1"
    if exist "src\%%m.hpp" set /a "good_modules+=1"
)

if !good_modules! lss 4 (
    echo WARNING: Few standard module names found
    echo Consider using: net.cpp, player.cpp, render.cpp, audio.cpp, etc.
)

:: ==========================================
:: FINAL VERDICT
:: ==========================================
echo.
if !has_error! equ 1 (
    echo ========================================
    echo BUILD REFUSED - Code quality issues!
    echo ========================================
    echo.
    if !split_abuse! gtr 0 (
        echo FAKE SPLITTING DETECTED!
        echo.
        echo BAD - Do not do this:
        echo   gameloop_1.cpp, gameloop_2.cpp, gameloop_3.cpp
        echo   render_part1.cpp, render_part2.cpp
        echo   main_continued.cpp, main_extra.cpp
        echo.
        echo GOOD - Proper modular design:
        echo   net.cpp       - Networking code
        echo   player.cpp    - Player logic
        echo   render.cpp    - Rendering
        echo   audio.cpp     - Sound system  
        echo   world.cpp     - World generation
        echo   menu.cpp      - UI/Menus
        echo   input.cpp     - Input handling
        echo   utils.cpp     - Utilities
        echo.
        echo Each module = ONE responsibility!
        echo NOT the same code split into chunks!
    )
    echo ========================================
    exit /b 1
)

echo All checks passed!
echo.

:: ==========================================
:: BUILD
:: ==========================================
if not exist "build" mkdir build

echo Compiling (Static Build)...
g++ -std=c++17 -O2 -Wall -Wno-unused-result -Wno-unknown-pragmas -mwindows -static -static-libgcc -static-libstdc++ ^
    -I"deps/include" ^
    -o "build/backrooms.exe" ^
    "src/game.cpp" ^
    "deps/src/glad.c" ^
    -L"deps/lib" ^
    -lglfw3 -lopengl32 -lgdi32 -luser32 -lkernel32 -lwinmm -lws2_32

if !errorlevel! neq 0 (
    echo.
    echo Build FAILED!
    exit /b 1
)

if exist "deps/lib/glfw3.dll" (
    copy /Y "deps/lib/glfw3.dll" "build\" >nul 2>&1
)

echo.
echo ========================================
echo Build successful!
echo ========================================
echo Run: build\backrooms.exe
echo.

exit /b 0