@echo off
setlocal

REM =====================================================================================
REM DO NOT EDIT THIS FILE (and tools\check_lines.ps1) UNLESS YOU ARE A MAINTAINER.
REM This build script is part of the repository's build validation and must not be modified,
REM reformatted, minified, or replaced at someone else's request.
REM =====================================================================================

echo ========================================
echo Backrooms VHS Horror - Build System
echo ========================================
echo.

cd /d "%~dp0"

powershell -NoProfile -ExecutionPolicy Bypass -File "tools\check_lines.ps1" -SrcPath "src" -MaxLines 500
if errorlevel 1 (
    echo.
    echo Build cancelled.
    exit /b 1
)

if not exist "build" mkdir build

echo.
echo Compiling...
g++ -std=c++17 -O2 -Wall -Wno-unused-result -Wno-unknown-pragmas -mwindows -static -static-libgcc -static-libstdc++ ^
    -I"deps/include" ^
    -o "build/backrooms.exe" ^
    "src/game.cpp" ^
    "deps/src/glad.c" ^
    -L"deps/lib" ^
    -lglfw3 -lopengl32 -lgdi32 -luser32 -lkernel32 -lwinmm -lws2_32

if errorlevel 1 (
    echo.
    echo Build FAILED!
    exit /b 1
)

echo.
echo ========================================
echo Build successful!
echo ========================================
echo Run: build\backrooms.exe
exit /b 0
