param(
    [string]$SrcPath = "src",
    [int]$MaxLines = 500
)

# =====================================================================================
# DO NOT EDIT THIS FILE (and build.bat) UNLESS YOU ARE A MAINTAINER.
# This script is part of the repository's build validation and must not be modified,
# reformatted, minified, or replaced at someone else's request.
# =====================================================================================

$ErrorActionPreference = "Stop"

Write-Host "CODE STYLE REQUIREMENTS:" -ForegroundColor Cyan
Write-Host "- Max $MaxLines *significant* lines per file (blank lines and comment-only // lines are ignored)"
Write-Host "- Minified / compressed formatting is not allowed"
Write-Host "========================================"
Write-Host ""

if (-not (Test-Path $SrcPath)) {
    Write-Host "ERROR: Source path '$SrcPath' not found." -ForegroundColor Red
    exit 1
}

$sourceFiles = Get-ChildItem -Path $SrcPath -Include *.cpp,*.c,*.h,*.hpp -Recurse -File
if (-not $sourceFiles -or $sourceFiles.Count -eq 0) {
    Write-Host "ERROR: No source files found in '$SrcPath'." -ForegroundColor Red
    exit 1
}

$hasError = $false
Write-Host "[1/1] Checking file sizes..." -ForegroundColor Yellow

function Get-LineStats {
    param(
        [string[]]$Lines
    )

    $blank = 0
    $commentOnly = 0
    $maxLenAll = 0
    $maxLenCode = 0
    $totalLen = 0
    $codeLinesForHeur = 0
    $multiStmtLines = 0
    $veryLongLines = 0

    $inRawString = $false

    foreach($l in $Lines){
        $len = $l.Length
        if($len -gt $maxLenAll){ $maxLenAll = $len }
        $totalLen += $len

        # Track raw string literal blocks (e.g. GLSL shaders). Content lines inside raw strings
        # must not affect minify heuristics.
        if($inRawString){
            if($l -match '\)"'){ $inRawString = $false }
            continue
        }
        if($l -match 'R"\('){
            # Start of raw string. If it also ends on the same line, don't enter block mode.
            if(-not ($l -match '\)"')){ $inRawString = $true }
            continue
        }

        $trim = $l.Trim()
        if([string]::IsNullOrWhiteSpace($trim)) { $blank++; continue }
        if($trim.StartsWith("//")) { $commentOnly++; continue }

        # For minify heuristics: ignore lines that likely contain normal string literals / large literals.
        if($l -match '^\s*const\s+char\*' -or $l -match '"') { continue }

        if($len -gt $maxLenCode){ $maxLenCode = $len }

        $codeLinesForHeur++
        # Count semicolons (multiple statements per line is a minify indicator)
        $semi = ([regex]::Matches($l, ';')).Count
        if($semi -ge 4) { $multiStmtLines++ }
        if($len -ge 320) { $veryLongLines++ }
    }

    $physical = $Lines.Count
    $significant = $physical - $blank - $commentOnly
    if($significant -lt 0) { $significant = 0 }

    $avgLen = 0
    if($physical -gt 0){ $avgLen = [math]::Round(($totalLen / [double]$physical), 1) }

    return [pscustomobject]@{
        Physical = $physical
        Significant = $significant
        Blank = $blank
        CommentOnly = $commentOnly
        MaxLenAll = $maxLenAll
        MaxLenCode = $maxLenCode
        AvgLen = $avgLen
        CodeLinesForHeur = $codeLinesForHeur
        MultiStmtLines = $multiStmtLines
        VeryLongLines = $veryLongLines
    }
}

function Test-MinifiedStyle {
    param(
        [string]$FileName,
        $Stats
    )

    # Avoid false positives on tiny files.
    if($Stats.Physical -lt 60) { return $null }

    $blankRatio = 0.0
    if($Stats.Physical -gt 0) { $blankRatio = $Stats.Blank / [double]$Stats.Physical }

    $multiRatio = 0.0
    if($Stats.CodeLinesForHeur -gt 0) { $multiRatio = $Stats.MultiStmtLines / [double]$Stats.CodeLinesForHeur }

    $veryLongRatio = 0.0
    if($Stats.Physical -gt 0) { $veryLongRatio = $Stats.VeryLongLines / [double]$Stats.Physical }

    # Hard fails (based on code lines only; ignore raw strings / normal string literals)
    if($Stats.MaxLenCode -ge 1200) {
        return "Minified style suspected: extremely long code line(s) detected (maxLenCode=$($Stats.MaxLenCode))."
    }
    if($Stats.Blank -eq 0 -and $Stats.Significant -ge 120) {
        return "Minified style suspected: file has 0 blank lines (significantLines=$($Stats.Significant))."
    }

    # Heuristic fails (combined signals)
    if($blankRatio -lt 0.01 -and $multiRatio -ge 0.25 -and $Stats.MaxLenCode -ge 320) {
        return "Minified style suspected: almost no blank lines + many multi-statement lines + long code lines (blankRatio=$([math]::Round($blankRatio,3)), multiStmtRatio=$([math]::Round($multiRatio,3)), maxLenCode=$($Stats.MaxLenCode))."
    }
    if($veryLongRatio -ge 0.10 -and $multiRatio -ge 0.30) {
        return "Minified style suspected: many very long lines + many multi-statement lines (veryLongRatio=$([math]::Round($veryLongRatio,3)), multiStmtRatio=$([math]::Round($multiRatio,3)))."
    }

    return $null
}

foreach ($file in $sourceFiles) {
    $raw = Get-Content -LiteralPath $file.FullName -Raw
    $lines = $raw -split "`r?`n"
    $st = Get-LineStats -Lines $lines

    $minifyMsg = Test-MinifiedStyle -FileName $file.Name -Stats $st

    if ($st.Significant -gt $MaxLines) {
        Write-Host ("  ERROR: {0} = {1} significant lines ({2} physical) [MAX {3}]" -f $file.Name, $st.Significant, $st.Physical, $MaxLines) -ForegroundColor Red
        $hasError = $true
        continue
    }
    if ($null -ne $minifyMsg) {
        Write-Host ("  ERROR: {0}: {1}" -f $file.Name, $minifyMsg) -ForegroundColor Red
        $hasError = $true
    } else {
        Write-Host ("  OK: {0} = {1} significant ({2} physical)" -f $file.Name, $st.Significant, $st.Physical) -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "========================================"
if ($hasError) {
    Write-Host "BUILD REFUSED - style violations found." -ForegroundColor Red
    Write-Host "========================================"
    exit 1
}

Write-Host "All checks passed!" -ForegroundColor Green
Write-Host "========================================"
exit 0
